# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nNode.proto\x12\x04node\"x\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncluster_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12!\n\x06\x61\x63\x63\x65ss\x18\x04 \x01(\x0e\x32\x11.node.AccessLevel\x12\x10\n\x08\x61rchived\x18\x05 \x01(\x08\x12\r\n\x05grade\x18\x06 \x01(\x05\"i\n\x11\x43reateNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12!\n\x06\x61\x63\x63\x65ss\x18\x03 \x01(\x0e\x32\x11.node.AccessLevel\x12\x12\n\ncluster_id\x18\x04 \x01(\t\"5\n\x0eGetNodeRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\":\n\x12GetAllNodesRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12\x10\n\x08\x61rchived\x18\x02 \x01(\x08\"g\n\x11UpdateNodeRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x61rchived\x18\x04 \x01(\x08\x12\r\n\x05grade\x18\x05 \x01(\x05\"K\n\x11\x44\x65leteNodeRequest\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x11\n\tpermanent\x18\x03 \x01(\x08\"6\n\tNodeReply\x12\x18\n\x04node\x18\x01 \x01(\x0b\x32\n.node.Node\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\rNodeListReply\x12\x19\n\x05nodes\x18\x01 \x03(\x0b\x32\n.node.Node*>\n\x0b\x41\x63\x63\x65ssLevel\x12\x16\n\x12\x41\x43\x43\x45SS_UNSPECIFIED\x10\x00\x12\n\n\x06PUBLIC\x10\x01\x12\x0b\n\x07PRIVATE\x10\x02\x32\xa5\x02\n\x0bNodeService\x12\x36\n\nCreateNode\x12\x17.node.CreateNodeRequest\x1a\x0f.node.NodeReply\x12\x30\n\x07GetNode\x12\x14.node.GetNodeRequest\x1a\x0f.node.NodeReply\x12<\n\x0bGetAllNodes\x12\x18.node.GetAllNodesRequest\x1a\x13.node.NodeListReply\x12\x36\n\nUpdateNode\x12\x17.node.UpdateNodeRequest\x1a\x0f.node.NodeReply\x12\x36\n\nDeleteNode\x12\x17.node.DeleteNodeRequest\x1a\x0f.node.NodeReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCESSLEVEL']._serialized_start=646
  _globals['_ACCESSLEVEL']._serialized_end=708
  _globals['_NODE']._serialized_start=20
  _globals['_NODE']._serialized_end=140
  _globals['_CREATENODEREQUEST']._serialized_start=142
  _globals['_CREATENODEREQUEST']._serialized_end=247
  _globals['_GETNODEREQUEST']._serialized_start=249
  _globals['_GETNODEREQUEST']._serialized_end=302
  _globals['_GETALLNODESREQUEST']._serialized_start=304
  _globals['_GETALLNODESREQUEST']._serialized_end=362
  _globals['_UPDATENODEREQUEST']._serialized_start=364
  _globals['_UPDATENODEREQUEST']._serialized_end=467
  _globals['_DELETENODEREQUEST']._serialized_start=469
  _globals['_DELETENODEREQUEST']._serialized_end=544
  _globals['_NODEREPLY']._serialized_start=546
  _globals['_NODEREPLY']._serialized_end=600
  _globals['_NODELISTREPLY']._serialized_start=602
  _globals['_NODELISTREPLY']._serialized_end=644
  _globals['_NODESERVICE']._serialized_start=711
  _globals['_NODESERVICE']._serialized_end=1004
# @@protoc_insertion_point(module_scope)
