# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backend.RealTimeChat_pb2 as RealTimeChat__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in RealTimeChat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartNew = channel.unary_unary(
                '/RealTimeChat.Chat/StartNew',
                request_serializer=RealTimeChat__pb2.ChatObject.SerializeToString,
                response_deserializer=RealTimeChat__pb2.ChatReply.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/RealTimeChat.Chat/Get',
                request_serializer=RealTimeChat__pb2.GetRequest.SerializeToString,
                response_deserializer=RealTimeChat__pb2.GetReply.FromString,
                _registered_method=True)
        self.StreamUpdates = channel.stream_stream(
                '/RealTimeChat.Chat/StreamUpdates',
                request_serializer=RealTimeChat__pb2.StreamRequest.SerializeToString,
                response_deserializer=RealTimeChat__pb2.StreamUpdate.FromString,
                _registered_method=True)


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartNew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdates(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartNew': grpc.unary_unary_rpc_method_handler(
                    servicer.StartNew,
                    request_deserializer=RealTimeChat__pb2.ChatObject.FromString,
                    response_serializer=RealTimeChat__pb2.ChatReply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=RealTimeChat__pb2.GetRequest.FromString,
                    response_serializer=RealTimeChat__pb2.GetReply.SerializeToString,
            ),
            'StreamUpdates': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamUpdates,
                    request_deserializer=RealTimeChat__pb2.StreamRequest.FromString,
                    response_serializer=RealTimeChat__pb2.StreamUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RealTimeChat.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RealTimeChat.Chat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartNew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RealTimeChat.Chat/StartNew',
            RealTimeChat__pb2.ChatObject.SerializeToString,
            RealTimeChat__pb2.ChatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RealTimeChat.Chat/Get',
            RealTimeChat__pb2.GetRequest.SerializeToString,
            RealTimeChat__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/RealTimeChat.Chat/StreamUpdates',
            RealTimeChat__pb2.StreamRequest.SerializeToString,
            RealTimeChat__pb2.StreamUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
