# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RealTimeChat.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'RealTimeChat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RealTimeChat.proto\x12\x0cRealTimeChat\"V\n\nChatObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"6\n\tChatReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"\x0c\n\nGetRequest\"1\n\x08GetReply\x12%\n\x03ret\x18\x01 \x03(\x0b\x32\x18.RealTimeChat.ChatObject\",\n\rStreamRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"D\n\x0cStreamUpdate\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08received\x18\x03 \x01(\x08\x32\xcc\x01\n\x04\x43hat\x12=\n\x08StartNew\x12\x18.RealTimeChat.ChatObject\x1a\x17.RealTimeChat.ChatReply\x12\x37\n\x03Get\x12\x18.RealTimeChat.GetRequest\x1a\x16.RealTimeChat.GetReply\x12L\n\rStreamUpdates\x12\x1b.RealTimeChat.StreamRequest\x1a\x1a.RealTimeChat.StreamUpdate(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RealTimeChat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATOBJECT']._serialized_start=36
  _globals['_CHATOBJECT']._serialized_end=122
  _globals['_CHATREPLY']._serialized_start=124
  _globals['_CHATREPLY']._serialized_end=178
  _globals['_GETREQUEST']._serialized_start=180
  _globals['_GETREQUEST']._serialized_end=192
  _globals['_GETREPLY']._serialized_start=194
  _globals['_GETREPLY']._serialized_end=243
  _globals['_STREAMREQUEST']._serialized_start=245
  _globals['_STREAMREQUEST']._serialized_end=289
  _globals['_STREAMUPDATE']._serialized_start=291
  _globals['_STREAMUPDATE']._serialized_end=359
  _globals['_CHAT']._serialized_start=362
  _globals['_CHAT']._serialized_end=566
# @@protoc_insertion_point(module_scope)
