# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backend.ServerStatus_pb2 as ServerStatus__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ServerStatus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CheckStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkStatus = channel.unary_unary(
                '/ServerStatus.Check/checkStatus',
                request_serializer=ServerStatus__pb2.StatusRequest.SerializeToString,
                response_deserializer=ServerStatus__pb2.StatusReply.FromString,
                _registered_method=True)


class CheckServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.checkStatus,
                    request_deserializer=ServerStatus__pb2.StatusRequest.FromString,
                    response_serializer=ServerStatus__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServerStatus.Check', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServerStatus.Check', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Check(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServerStatus.Check/checkStatus',
            ServerStatus__pb2.StatusRequest.SerializeToString,
            ServerStatus__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
