# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ServerStatus.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ServerStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ServerStatus.proto\x12\x0cServerStatus\"\x0f\n\rStatusRequest\"\x1e\n\x0bStatusReply\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32N\n\x05\x43heck\x12\x45\n\x0b\x63heckStatus\x12\x1b.ServerStatus.StatusRequest\x1a\x19.ServerStatus.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ServerStatus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=36
  _globals['_STATUSREQUEST']._serialized_end=51
  _globals['_STATUSREPLY']._serialized_start=53
  _globals['_STATUSREPLY']._serialized_end=83
  _globals['_CHECK']._serialized_start=85
  _globals['_CHECK']._serialized_end=163
# @@protoc_insertion_point(module_scope)
